---
name: MQTT schemas
desc: pykwalify schemas for 'mqtt' plugin block, mqtt_publish, and mqtt_response

initialisation:
  flask:
    required: false
    type: map
    mapping:
      app:
        required: false
        type: map
        mapping:
          location:
            type: str
            required: false
