---
$schema: "http://json-schema.org/draft-07/schema#"

title: Flask schema
description: jsonschema for Flask connection

properties:
  flask:
    type: object
    properties:
      app:
        type: object
        properties:
          location:
            type: string
